# Generated by Django 4.2.7 on 2023-11-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election_poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcedpuresults',
            name='polling_unit_uniqueid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='announced_polling', to='election_poll.pollingunit'),
        ),
    ]
